### ISSUE TITLE
Decoding error with garbage text

### ISSUE THREAD

**Issue by zalexk** [QAQ-0203/Simple_BaseN-ASCII_Converter#1]
![recording](https://github.com/user-attachments/assets/e6dfd9d1-b562-4599-9c80-4a75543a63ae)

When I encode a complex type of string, with Chinese character, punctuation, digits and blanks. It cannot decoded properly with garbage text.

**Comment by zalexk** [comment]
**More details :**
The base is 2 and the map is `QA`.

**Comment by Ofeng0203** [comment]
It is a Simple Encoder/Decoder between ASCII and Base N. Chinese characters are not contained in ASCII character set.

![image](https://github.com/user-attachments/assets/7f367062-d0d5-4a6f-96d1-37e7e899ad27)

However, you can still use complex types of strings, such as the UTF-8 character set, to form your Map.

![Decoding error with garbage text #1](https://github.com/user-attachments/assets/e6812f1d-e7d7-4c4b-8c7b-141c12146a3e)
